`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: recovery_ctrl
// Generated: 2026-07-13
// Source: 053 architecture
module recovery_ctrl (
    input  logic commit_fire_i,
    input  core_types_pkg::scoreboard_entry_t commit_entry_i,
    input  logic [31:0] mtvec_i,
    input  logic [31:0] mepc_i,
    input  logic interrupt_valid_i,
    input  logic [31:0] interrupt_cause_i,
    input  logic branch_miss_i,
    input  logic [31:0] branch_actual_next_i,
    output logic full_flush_o,
    output logic redirect_valid_o,
    output logic [31:0] redirect_target_o
);
    import core_types_pkg::*;

    always_comb begin
        full_flush_o = interrupt_valid_i ||
                       (commit_fire_i &&
                        (commit_entry_i.exception_valid ||
                         commit_entry_i.sys_op == SYS_MRET ||
                         commit_entry_i.sys_op == SYS_FENCE_I));
        redirect_valid_o = full_flush_o || branch_miss_i;
        if (interrupt_valid_i) begin
            redirect_target_o = {mtvec_i[31:2], 2'b00};
            if (mtvec_i[1:0] == 2'b01)
                redirect_target_o = {mtvec_i[31:2], 2'b00} +
                                    {interrupt_cause_i[29:0], 2'b00};
        end else if (commit_entry_i.exception_valid)
            redirect_target_o = {mtvec_i[31:2], 2'b00};
        else if (commit_entry_i.sys_op == SYS_MRET) redirect_target_o = mepc_i;
        else if (commit_entry_i.sys_op == SYS_FENCE_I)
            redirect_target_o = commit_entry_i.pc + 32'd4;
        else redirect_target_o = branch_actual_next_i;
    end

`ifndef SYNTHESIS
    always_comb begin
        if (full_flush_o) assert (commit_fire_i || interrupt_valid_i);
        if (commit_fire_i && commit_entry_i.exception_valid)
            assert (redirect_target_o == {mtvec_i[31:2], 2'b00});
    end
`endif
endmodule
