rtl/common/pkg/soc_config_pkg.sv
rtl/common/pkg/memory_map_pkg.sv
rtl/common/pkg/common_types_pkg.sv
rtl/bus/hxi/hxi_pkg.sv
rtl/cpu/interface/cpu_mem_if.sv
rtl/memory/interface/mem_native_pkg.sv
rtl/cpu/pkg/cpu_config_pkg.sv
rtl/cpu/pkg/cpu_types_pkg.sv
rtl/common/sync/reset_sync.sv
rtl/common/sync/cdc_sync_level.sv
rtl/common/util/skid_buffer.sv
# biRISC-V core and direct TCM adapters
+incdir+rtl/cpu/biriscv/core
rtl/cpu/biriscv/core/biriscv_alu.v
rtl/cpu/biriscv/core/biriscv_csr.v
rtl/cpu/biriscv/core/biriscv_csr_regfile.v
rtl/cpu/biriscv/core/biriscv_decode.v
rtl/cpu/biriscv/core/biriscv_decoder.v
rtl/cpu/biriscv/core/biriscv_divider.v
rtl/cpu/biriscv/core/biriscv_exec.v
rtl/cpu/biriscv/core/biriscv_fetch.v
rtl/cpu/biriscv/core/biriscv_frontend.v
rtl/cpu/biriscv/core/biriscv_issue.v
rtl/cpu/biriscv/core/biriscv_lsu.v
rtl/cpu/biriscv/core/biriscv_mmu.v
rtl/cpu/biriscv/core/biriscv_multiplier.v
rtl/cpu/biriscv/core/biriscv_npc.v
rtl/cpu/biriscv/core/biriscv_pipe_ctrl.v
rtl/cpu/biriscv/core/biriscv_regfile.v
rtl/cpu/biriscv/core/biriscv_trace_sim.v
rtl/cpu/biriscv/core/biriscv_xilinx_2r1w.v
rtl/cpu/biriscv/core/riscv_core.v
rtl/cpu/biriscv/biriscv_itcm_adapter.sv
rtl/cpu/biriscv/biriscv_dtcm_adapter.sv
rtl/cpu/biriscv/biriscv_cpu_core.sv
rtl/cpu/cpu_subsystem.sv
rtl/bus/hxi/hxi_default_slave.sv
rtl/bus/hxi/hxi_crossbar.sv
rtl/bus/hxi/hxi_peripheral_router.sv
rtl/bus/bridge/hxi_async_bridge.sv
rtl/bus/bridge/hxi_to_apb.sv
rtl/bus/bridge/apb_interconnect.sv
rtl/memory/tcm/itcm_64_dp.sv
rtl/memory/tcm/dtcm_32_dp.sv
rtl/memory/tcm/cpu_tcm_router.sv
rtl/peripheral/timer/machine_timer.sv
rtl/peripheral/irq/interrupt_controller.sv
rtl/peripheral/uart/uart_fifo.sv
rtl/peripheral/uart/uart_tx.sv
rtl/peripheral/uart/uart_rx.sv
rtl/peripheral/uart/apb_uart.sv
rtl/peripheral/gpio/apb_gpio.sv
rtl/peripheral/test_status/apb_test_status.sv
rtl/soc/soc_core.sv
rtl/soc/soc_top_generic.sv
