rtl/common/pkg/soc_config_pkg.sv
+incdir+rtl/cpu/superscalar/fpu/vendor/fpnew
rtl/common/pkg/memory_map_pkg.sv
rtl/common/pkg/common_types_pkg.sv
rtl/bus/hxi/hxi_pkg.sv
rtl/memory/interface/mem_native_pkg.sv
rtl/cpu/pkg/cpu_config_pkg.sv
rtl/cpu/pkg/cpu_types_pkg.sv
rtl/cpu/superscalar/pkg/core_config_pkg.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/common_cells/cf_math_pkg.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_pkg.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/defs_div_sqrt_mvp.sv
rtl/cpu/superscalar/pkg/core_types_pkg.sv
rtl/common/sync/reset_sync.sv
rtl/common/util/skid_buffer.sv
# biRISC-V core and HXI-native caches
+incdir+rtl/cpu/biriscv/core
rtl/cpu/biriscv/core/biriscv_alu.v
rtl/cpu/biriscv/core/biriscv_csr.v
rtl/cpu/biriscv/core/biriscv_csr_regfile.v
rtl/cpu/biriscv/core/biriscv_decode.v
rtl/cpu/biriscv/core/biriscv_decoder.v
rtl/cpu/biriscv/core/biriscv_divider.v
rtl/cpu/biriscv/core/biriscv_exec.v
rtl/cpu/biriscv/core/biriscv_fetch.v
rtl/cpu/biriscv/core/biriscv_frontend.v
rtl/cpu/biriscv/core/biriscv_issue.v
rtl/cpu/biriscv/core/biriscv_lsu.v
rtl/cpu/biriscv/core/biriscv_mmu.v
rtl/cpu/biriscv/core/biriscv_multiplier.v
rtl/cpu/biriscv/core/biriscv_npc.v
rtl/cpu/biriscv/core/biriscv_pipe_ctrl.v
rtl/cpu/biriscv/core/biriscv_regfile.v
rtl/cpu/biriscv/core/biriscv_trace_sim.v
rtl/cpu/biriscv/core/biriscv_xilinx_2r1w.v
rtl/cpu/biriscv/core/riscv_core.v
rtl/cpu/biriscv/icache/icache_tag_ram.v
rtl/cpu/biriscv/icache/icache_data_ram.v
rtl/cpu/biriscv/icache/icache.v
rtl/cpu/biriscv/dcache/dcache_core_tag_ram.v
rtl/cpu/biriscv/dcache/dcache_core_data_ram.v
rtl/cpu/biriscv/dcache/dcache_if_pmem.v
rtl/cpu/biriscv/dcache/dcache_pmem_mux.v
rtl/cpu/biriscv/dcache/dcache_mux.v
rtl/cpu/biriscv/dcache/dcache_core.v
rtl/cpu/biriscv/dcache/dcache_hxi.v
rtl/cpu/biriscv/dcache/dcache.v
rtl/cpu/biriscv/biriscv_cpu_core.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/common_cells/lzc.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/common_cells/rr_arb_tree.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/control_mvp.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/iteration_div_sqrt_mvp.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/norm_div_sqrt_mvp.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/nrbd_nrsc_mvp.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/preprocess_mvp.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/div_sqrt_top_mvp.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/divsqrt/div_sqrt_mvp_wrapper.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_rounding.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_classifier.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_fma.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_fma_multi.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_cast_multi.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_noncomp.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_divsqrt_multi.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_opgroup_fmt_slice.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_opgroup_multifmt_slice.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_opgroup_block.sv
rtl/cpu/superscalar/fpu/vendor/fpnew/src/fpnew_top.sv
rtl/cpu/superscalar/fpu/fp_regfile.sv
rtl/cpu/superscalar/fpu/fp_execute_unit.sv
rtl/cpu/superscalar/fpu/fp_memory_unit.sv
rtl/cpu/superscalar/decode/decoder.sv
rtl/cpu/superscalar/frontend/fetch_queue.sv
rtl/cpu/superscalar/frontend/branch_predictor.sv
rtl/cpu/superscalar/frontend/frontend.sv
rtl/cpu/superscalar/issue/regfile.sv
rtl/cpu/superscalar/issue/scoreboard.sv
rtl/cpu/superscalar/issue/operand_resolver.sv
rtl/cpu/superscalar/issue/issue_control.sv
rtl/cpu/superscalar/commit/csr_file.sv
rtl/cpu/superscalar/control/recovery_ctrl.sv
rtl/cpu/superscalar/perf/perf_counters.sv
rtl/cpu/superscalar/execute/fixed_execute.sv
rtl/cpu/superscalar/execute/bitmanip_unit.sv
rtl/cpu/superscalar/ip/MUL_0.sv
rtl/cpu/superscalar/ip/DIV_0.sv
rtl/cpu/superscalar/execute/muldiv_unit.sv
rtl/cpu/superscalar/memory/dcache_tag_bank.sv
rtl/cpu/superscalar/memory/dcache_data_bank.sv
rtl/cpu/superscalar/memory/dmem_regslice.sv
rtl/cpu/superscalar/memory/dcache.sv
rtl/cpu/superscalar/memory/store_buffer.sv
rtl/cpu/superscalar/memory/load_queue.sv
rtl/cpu/superscalar/memory/store_forwarding.sv
rtl/cpu/superscalar/memory/memory_request_arbiter.sv
rtl/cpu/superscalar/memory/load_data_path.sv
rtl/cpu/superscalar/debug/commit_trace_probe.sv
rtl/cpu/superscalar/core_top.sv
rtl/cpu/superscalar/superscalar_cpu_core.sv
rtl/cpu/cpu_subsystem.sv
rtl/bus/hxi/hxi_default_slave.sv
rtl/bus/hxi/hxi_crossbar.sv
rtl/bus/bridge/hxi_to_apb.sv
rtl/bus/bridge/apb_interconnect.sv
rtl/memory/adapter/hxi_code_mem_slave.sv
rtl/memory/adapter/hxi_data_mem_slave.sv
rtl/memory/generic/generic_rom.sv
rtl/memory/generic/generic_spram.sv
rtl/memory/memory_subsystem.sv
rtl/peripheral/timer/machine_timer.sv
rtl/peripheral/irq/interrupt_controller.sv
rtl/peripheral/uart/uart_fifo.sv
rtl/peripheral/uart/uart_tx.sv
rtl/peripheral/uart/uart_rx.sv
rtl/peripheral/uart/apb_uart.sv
rtl/peripheral/gpio/apb_gpio.sv
rtl/peripheral/test_status/apb_test_status.sv
rtl/soc/soc_core.sv
rtl/soc/soc_top_generic.sv
