rtl/common/pkg/soc_config_pkg.sv
rtl/common/pkg/memory_map_pkg.sv
rtl/common/pkg/common_types_pkg.sv
rtl/bus/hxi/hxi_pkg.sv
rtl/memory/interface/mem_native_pkg.sv
rtl/cpu/pkg/cpu_config_pkg.sv
rtl/cpu/pkg/cpu_types_pkg.sv
rtl/cpu/superscalar/pkg/core_config_pkg.sv
rtl/cpu/superscalar/pkg/core_types_pkg.sv
rtl/common/sync/reset_sync.sv
rtl/common/util/skid_buffer.sv
rtl/cpu/superscalar/decode/decoder.sv
rtl/cpu/superscalar/frontend/fetch_queue.sv
rtl/cpu/superscalar/frontend/branch_predictor.sv
rtl/cpu/superscalar/frontend/frontend.sv
rtl/cpu/superscalar/issue/regfile.sv
rtl/cpu/superscalar/issue/scoreboard.sv
rtl/cpu/superscalar/issue/operand_resolver.sv
rtl/cpu/superscalar/issue/issue_control.sv
rtl/cpu/superscalar/commit/csr_file.sv
rtl/cpu/superscalar/control/recovery_ctrl.sv
rtl/cpu/superscalar/perf/perf_counters.sv
rtl/cpu/superscalar/execute/fixed_execute.sv
rtl/cpu/superscalar/execute/bitmanip_unit.sv
rtl/cpu/superscalar/ip/MUL_0.sv
rtl/cpu/superscalar/ip/DIV_0.sv
rtl/cpu/superscalar/execute/muldiv_unit.sv
rtl/cpu/superscalar/memory/dcache_tag_bank.sv
rtl/cpu/superscalar/memory/dcache_data_bank.sv
rtl/cpu/superscalar/memory/dmem_regslice.sv
rtl/cpu/superscalar/memory/dcache.sv
rtl/cpu/superscalar/memory/store_buffer.sv
rtl/cpu/superscalar/memory/load_queue.sv
rtl/cpu/superscalar/memory/store_forwarding.sv
rtl/cpu/superscalar/memory/memory_request_arbiter.sv
rtl/cpu/superscalar/memory/load_data_path.sv
rtl/cpu/superscalar/debug/commit_trace_probe.sv
rtl/cpu/superscalar/core_top.sv
rtl/cpu/superscalar/superscalar_cpu_core.sv
rtl/cpu/cpu_subsystem.sv
rtl/bus/hxi/hxi_default_slave.sv
rtl/bus/hxi/hxi_crossbar.sv
rtl/bus/bridge/hxi_to_apb.sv
rtl/bus/bridge/apb_interconnect.sv
rtl/memory/adapter/hxi_code_mem_slave.sv
rtl/memory/adapter/hxi_data_mem_slave.sv
rtl/memory/generic/generic_rom.sv
rtl/memory/generic/generic_spram.sv
rtl/memory/memory_subsystem.sv
rtl/peripheral/timer/machine_timer.sv
rtl/peripheral/irq/interrupt_controller.sv
rtl/peripheral/uart/uart_fifo.sv
rtl/peripheral/uart/uart_tx.sv
rtl/peripheral/uart/uart_rx.sv
rtl/peripheral/uart/apb_uart.sv
rtl/peripheral/gpio/apb_gpio.sv
rtl/peripheral/test_status/apb_test_status.sv
rtl/soc/soc_core.sv
rtl/soc/soc_top_generic.sv
