`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: regfile
// Generated: 2026-07-13
// Source: 053 architecture
module regfile (
    input  logic clk,
    input  logic rst,
    input  logic [4:0] rs1_addr_i,
    input  logic [4:0] rs2_addr_i,
    input  logic [4:0] rs3_addr_i,
    output logic [31:0] rs1_data_o,
    output logic [31:0] rs2_data_o,
    output logic [31:0] rs3_data_o,
    input  logic write_valid_i,
    input  logic [4:0] write_addr_i,
    input  logic [31:0] write_data_i
);
    logic [31:0] regs_q [0:31];
    assign rs1_data_o = (rs1_addr_i == 0) ? 32'd0 : regs_q[rs1_addr_i];
    assign rs2_data_o = (rs2_addr_i == 0) ? 32'd0 : regs_q[rs2_addr_i];
    assign rs3_data_o = (rs3_addr_i == 0) ? 32'd0 : regs_q[rs3_addr_i];

    // RV32 does not define reset values for x1..x31.  Resetting all 1024 data
    // bits created a global high-fanout reset path without adding architectural
    // state.  Only x0 is physically maintained at zero.
    always_ff @(posedge clk) begin
        if (write_valid_i && write_addr_i != 0) regs_q[write_addr_i] <= write_data_i;
        regs_q[0] <= 32'd0;
    end

`ifndef SYNTHESIS
    always_ff @(posedge clk) if (!rst) assert (regs_q[0] == 0);
`endif
endmodule
