`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: core_types_pkg
// Generated: 2026-07-13
// Source: 053_superscalar_framework_inorder_single_issue_core_architecture.md
package core_types_pkg;
    import core_config_pkg::*;

    typedef enum logic [3:0] {
        FU_ALU, FU_BRANCH, FU_LOAD, FU_STORE, FU_MULDIV, FU_SYSTEM,
        FU_NONE, FU_BITMANIP, FU_FP, FU_FP_MEM
    } fu_e;

    typedef enum logic [4:0] {
        FP_ADD, FP_SUB, FP_MUL, FP_DIV, FP_SQRT,
        FP_FMADD, FP_FMSUB, FP_FNMSUB, FP_FNMADD,
        FP_SGNJ, FP_SGNJN, FP_SGNJX, FP_MIN, FP_MAX,
        FP_EQ, FP_LT, FP_LE, FP_CLASS,
        FP_F2I, FP_I2F, FP_F2F, FP_MV_X_W, FP_MV_W_X,
        FP_LOAD, FP_STORE
    } fp_op_e;

    typedef enum logic [3:0] {
        ALU_ADD, ALU_SUB, ALU_AND, ALU_OR, ALU_XOR, ALU_SLL, ALU_SRL,
        ALU_SRA, ALU_SLT, ALU_SLTU, ALU_COPY_B
    } alu_op_e;

    typedef enum logic [5:0] {
        BM_SH1ADD, BM_SH2ADD, BM_SH3ADD,
        BM_ANDN, BM_CLZ, BM_CPOP, BM_CTZ, BM_MAX, BM_MAXU, BM_MIN, BM_MINU,
        BM_ORC_B, BM_ORN, BM_REV8, BM_ROL, BM_ROR, BM_SEXT_B, BM_SEXT_H,
        BM_XNOR, BM_ZEXT_H,
        BM_CLMUL, BM_CLMULH, BM_CLMULR,
        BM_BREV8, BM_PACK, BM_PACKH, BM_UNZIP, BM_ZIP,
        BM_XPERM4, BM_XPERM8,
        BM_BCLR, BM_BEXT, BM_BINV, BM_BSET
    } bitmanip_op_e;

    typedef enum logic [2:0] {
        BR_NONE, BR_BEQ, BR_BNE, BR_BLT, BR_BGE, BR_BLTU, BR_BGEU
    } branch_op_e;

    typedef enum logic [2:0] {
        M_MUL, M_MULH, M_MULHSU, M_MULHU, M_DIV, M_DIVU, M_REM, M_REMU
    } muldiv_op_e;

    typedef enum logic [2:0] {
        CSR_NONE, CSR_WRITE, CSR_SET, CSR_CLEAR
    } csr_op_e;

    typedef enum logic [3:0] {
        SYS_NONE, SYS_CSR, SYS_ECALL, SYS_EBREAK, SYS_MRET, SYS_FENCE,
        SYS_FENCE_I
    } sys_op_e;

    typedef enum logic [1:0] {MEM_BYTE, MEM_HALF, MEM_WORD} mem_size_e;
    typedef enum logic [1:0] {PRED_NONE, PRED_COND, PRED_JUMP, PRED_RETURN} pred_kind_e;

    typedef struct packed {
        logic [31:0] pc;
        logic [31:0] instr;
        logic        access_fault;
        logic [31:0] pred_next_pc;
        pred_kind_e  pred_kind;
        logic        pred_hit;
        logic [1:0]  pred_counter;
        logic [GSHARE_HISTORY_BITS-1:0] pred_index;
    } fetch_entry_t;

    typedef struct packed {
        logic [31:0] pc;
        logic [31:0] instr;
        logic [4:0]  rs1;
        logic [4:0]  rs2;
        logic [4:0]  rd;
        logic [4:0]  frs1;
        logic [4:0]  frs2;
        logic [4:0]  frs3;
        logic [4:0]  frd;
        logic        uses_rs1;
        logic        uses_rs2;
        logic        writes_rd;
        logic        uses_frs1;
        logic        uses_frs2;
        logic        uses_frs3;
        logic        writes_frd;
        logic [31:0] imm;
        fu_e         fu;
        alu_op_e     alu_op;
        bitmanip_op_e bitmanip_op;
        branch_op_e  branch_op;
        muldiv_op_e  muldiv_op;
        fp_op_e      fp_op;
        logic        fp_fmt;
        logic        fp_dst_fmt;
        logic [2:0]  fp_rm;
        logic        fp_rm_used;
        logic        fp_unsigned;
        mem_size_e   mem_size;
        logic        load_unsigned;
        logic        is_jal;
        logic        is_jalr;
        logic [31:0] pred_next_pc;
        pred_kind_e  pred_kind;
        logic        pred_hit;
        logic [1:0]  pred_counter;
        logic [GSHARE_HISTORY_BITS-1:0] pred_index;
        sys_op_e     sys_op;
        csr_op_e     csr_op;
        logic [11:0] csr_addr;
        logic        csr_imm;
        logic        serialize;
        logic        exception_valid;
        logic [4:0]  exception_cause;
        logic [31:0] exception_tval;
    } uop_t;

    typedef struct packed {
        logic        occupied;
        logic        done;
        logic [31:0] pc;
        logic [31:0] instr;
        logic [4:0]  rd;
        logic        writes_rd;
        logic [31:0] result;
        logic [4:0]  frd;
        logic        writes_frd;
        logic [31:0] fp_result;
        logic [4:0]  fp_flags;
        logic        fp_dirty;
        fp_op_e      fp_op;
        fu_e         fu;
        logic        serialize;
        sys_op_e     sys_op;
        csr_op_e     csr_op;
        logic [11:0] csr_addr;
        logic [31:0] csr_src;
        logic        exception_valid;
        logic [4:0]  exception_cause;
        logic [31:0] exception_tval;
        logic        store_slot_valid;
        logic [STORE_ID_W-1:0] store_slot;
        logic        is_call;
        logic        is_return;
        logic [31:0] link_addr;
    } scoreboard_entry_t;

    typedef struct packed {
        logic valid;
        logic [TRANS_ID_W-1:0] trans_id;
        logic [31:0] result;
        logic exception_valid;
        logic [4:0] exception_cause;
        logic [31:0] exception_tval;
        logic store_slot_valid;
        logic [STORE_ID_W-1:0] store_slot;
    } completion_t;

    typedef struct packed {
        logic        valid;
        logic [TRANS_ID_W-1:0] trans_id;
        logic [31:0] int_result;
        logic [31:0] fp_result;
        logic [4:0]  fp_flags;
        logic        writes_rd;
        logic        writes_frd;
        logic        exception_valid;
        logic [4:0]  exception_cause;
        logic [31:0] exception_tval;
    } fp_completion_t;

    typedef struct packed {
        logic valid;
        logic [TRANS_ID_W-1:0] trans_id;
        uop_t uop;
        logic [31:0] op1;
        logic [31:0] op2;
        logic [31:0] fp_op1;
        logic [31:0] fp_op2;
        logic [31:0] fp_op3;
    } exec_req_t;

    typedef struct packed {
        logic valid;
        logic [TRANS_ID_W-1:0] trans_id;
        logic [31:0] addr;
        mem_size_e size;
        logic load_unsigned;
        logic [7:0] store_seq_cutoff;
        logic [3:0] forward_mask;
        logic [31:0] forward_data;
    } load_entry_t;

    typedef struct packed {
        logic valid;
        logic [TRANS_ID_W-1:0] trans_id;
        logic [7:0] store_seq;
        logic [31:0] addr;
        logic [31:0] wdata;
        logic [3:0] wstrb;
        logic uncached;
    } store_entry_t;
endpackage
