`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: core_config_pkg
// Generated: 2026-07-13
// Source: 053_superscalar_framework_inorder_single_issue_core_architecture.md
package core_config_pkg;
    // Select the bit-manipulation profile before elaboration.  Keep all six
    // disabled for the timing-identical RV32IM baseline; enable only the group
    // required by the competition image.
    localparam logic CFG_ZBA              = 1'b0;
    localparam logic CFG_ZBB              = 1'b0;
    localparam logic CFG_ZBC              = 1'b0;
    localparam logic CFG_ZBKB             = 1'b0;
    localparam logic CFG_ZBKX             = 1'b0;
    localparam logic CFG_ZBS              = 1'b0;
    localparam logic CFG_ZB_ANY           = CFG_ZBA | CFG_ZBB | CFG_ZBC |
                                             CFG_ZBKB | CFG_ZBKX | CFG_ZBS;

    localparam int unsigned XLEN               = 32;
    // SocRV is the integration authority.  Keep the imported core's reset and
    // cache windows tied to the generated SoC contract instead of duplicating
    // addresses from the original teaching platform.
    localparam logic [31:0] RESET_PC           = cpu_config_pkg::CPU_RESET_VECTOR;
    localparam int unsigned IROM_BYTE_ADDR_W   = 14;
    localparam int unsigned FETCH_QUEUE_DEPTH  = 4;
    localparam int unsigned SCOREBOARD_DEPTH   = 8;
    // Keep more independent memory operations in flight.  These depths stay
    // bounded by the eight-entry retirement scoreboard; no extra combinational
    // cache/HXI stage is introduced by the capacity increase.
    localparam int unsigned STORE_BUFFER_DEPTH = 8;
    localparam int unsigned LOAD_QUEUE_DEPTH   = 4;
    // Increase direct-mapped BTB capacity without changing predictor policy,
    // history or update rules.  Extra index bits can only split conflicts that
    // existed in the smaller table; they cannot merge previously distinct
    // indices.  The 512-entry payload uses two 18 Kb block RAMs.
    localparam int unsigned BTB_ENTRIES        = 512;
    localparam int unsigned GSHARE_HISTORY_BITS = 8;
    localparam int unsigned GSHARE_PHT_ENTRIES  = 1 << GSHARE_HISTORY_BITS;
    localparam int unsigned RAS_DEPTH          = 8;
    localparam int unsigned DCACHE_LINES       = 2048;
    localparam int unsigned DCACHE_LINE_BYTES  = 16;
    localparam logic [31:0] DRAM_START          = memory_map_pkg::DATA_BASE;
    localparam logic [31:0] DRAM_END            = memory_map_pkg::DATA_BASE +
                                                   memory_map_pkg::DATA_SIZE;
    localparam int unsigned TRANS_ID_W          = $clog2(SCOREBOARD_DEPTH);
    localparam int unsigned STORE_ID_W          = $clog2(STORE_BUFFER_DEPTH);
endpackage
