/* Generated by scripts/generate_soc_contract.py; do not edit. */
#ifndef SOCRV_SOC_IRQ_H
#define SOCRV_SOC_IRQ_H

#define SOCRV_MCAUSE_TIMER 7u
#define SOCRV_MIE_TIMER_MASK (1u << 7)


#endif /* SOCRV_SOC_IRQ_H */
