/* Generated by scripts/generate_soc_contract.py; do not edit. */
#ifndef SOCRV_SOC_CONFIG_H
#define SOCRV_SOC_CONFIG_H

#define SOCRV_XLEN 32u
#define SOCRV_MARCH "rv32i_zicsr"
#define SOCRV_MABI "ilp32"
#define SOCRV_SOC_CLOCK_HZ 50000000u
#define SOCRV_TIMER_CLOCK_HZ 50000000u
#define SOCRV_UART_BAUD 115200u
#define SOCRV_UART_DIVISOR (SOCRV_SOC_CLOCK_HZ / SOCRV_UART_BAUD)

#endif /* SOCRV_SOC_CONFIG_H */
