# Generated by scripts/generate_soc_contract.py; do not edit.
SOCRV_MARCH := rv32imf_zicsr_zicntr_zifencei
SOCRV_MABI := ilp32f
SOCRV_SOC_CLOCK_HZ := 120000000
SOCRV_PERIPH_CLOCK_HZ := 50000000
SOCRV_TIMER_CLOCK_HZ := 120000000
SOCRV_UART_BAUD := 115200
