/* Generated by scripts/generate_soc_contract.py; do not edit. */
#ifndef SOCRV_SOC_IRQ_H
#define SOCRV_SOC_IRQ_H

#define SOCRV_MCAUSE_SOFTWARE 3u
#define SOCRV_MIE_SOFTWARE_MASK (1u << 3)
#define SOCRV_MCAUSE_TIMER 7u
#define SOCRV_MIE_TIMER_MASK (1u << 7)
#define SOCRV_MCAUSE_EXTERNAL 11u
#define SOCRV_MIE_EXTERNAL_MASK (1u << 11)

#define SOCRV_EXT_IRQ_UART 0u
#define SOCRV_EXT_IRQ_UART_MASK (1u << 0)

#endif /* SOCRV_SOC_IRQ_H */
