rtl/common/pkg/soc_config_pkg.sv
rtl/common/pkg/memory_map_pkg.sv
rtl/common/pkg/common_types_pkg.sv
rtl/bus/hxi/hxi_pkg.sv
rtl/memory/interface/mem_native_pkg.sv
rtl/cpu/pkg/cpu_config_pkg.sv
rtl/cpu/pkg/cpu_types_pkg.sv
rtl/common/sync/reset_sync.sv
rtl/common/util/skid_buffer.sv
rtl/cpu/demo/demo_cpu_core.sv
rtl/cpu/cpu_subsystem.sv
rtl/bus/hxi/hxi_default_slave.sv
rtl/bus/hxi/hxi_crossbar.sv
rtl/bus/bridge/hxi_to_apb.sv
rtl/bus/bridge/apb_interconnect.sv
rtl/memory/adapter/hxi_code_mem_slave.sv
rtl/memory/adapter/hxi_data_mem_slave.sv
rtl/memory/generic/generic_rom.sv
rtl/memory/generic/generic_spram.sv
rtl/memory/memory_subsystem.sv
rtl/peripheral/timer/machine_timer.sv
rtl/peripheral/irq/interrupt_controller.sv
rtl/peripheral/uart/uart_fifo.sv
rtl/peripheral/uart/uart_tx.sv
rtl/peripheral/uart/uart_rx.sv
rtl/peripheral/uart/apb_uart.sv
rtl/peripheral/gpio/apb_gpio.sv
rtl/peripheral/test_status/apb_test_status.sv
rtl/soc/soc_core.sv
rtl/soc/soc_top_generic.sv
