from __future__ import annotations

import argparse
import json
from pathlib import Path

from lib.repo import repo_path


OUTPUTS = {
    "memory": repo_path("software", "bsp", "include", "soc_memory_map.h"),
    "config": repo_path("software", "bsp", "include", "soc_config.h"),
    "irq": repo_path("software", "bsp", "include", "soc_irq.h"),
    "registers": repo_path("software", "bsp", "include", "soc_registers.h"),
    "linker": repo_path("software", "linker", "memory.ldh"),
}


def load_documents() -> tuple[dict[str, object], dict[str, object]]:
    memory_map = json.loads(
        repo_path("data", "soc", "memory_map.json").read_text(encoding="utf-8")
    )
    contract = json.loads(
        repo_path("data", "soc", "software_contract.json").read_text(
            encoding="utf-8"
        )
    )
    return memory_map, contract


def hex_value(value: str) -> int:
    return int(value, 0)


def header_guard(name: str, body: list[str]) -> str:
    return "\n".join(
        [
            "/* Generated by scripts/generate_soc_contract.py; do not edit. */",
            f"#ifndef {name}",
            f"#define {name}",
            "",
            *body,
            "",
            f"#endif /* {name} */",
            "",
        ]
    )


def render_memory(memory_map: dict[str, object]) -> str:
    body: list[str] = []
    for name, region in memory_map["regions"].items():
        body.append(
            f"#define SOCRV_{name}_BASE "
            f"0x{hex_value(region['base']):08x}u"
        )
        body.append(
            f"#define SOCRV_{name}_SIZE "
            f"0x{hex_value(region['size']):08x}u"
        )
    body.extend(
        [
            "",
            f"#define SOCRV_RESET_VECTOR "
            f"0x{hex_value(memory_map['reset_vector']):08x}u",
        ]
    )
    return header_guard("SOCRV_SOC_MEMORY_MAP_H", body)


def render_config(contract: dict[str, object]) -> str:
    cpu = contract["cpu"]
    clocks = contract["clocks"]
    body = [
        f"#define SOCRV_XLEN {cpu['xlen']}u",
        f"#define SOCRV_MARCH \"{cpu['march']}\"",
        f"#define SOCRV_MABI \"{cpu['mabi']}\"",
        f"#define SOCRV_CPU_IMPLEMENTATION \"{cpu['implementation']['name']}\"",
        f"#define SOCRV_TARGET_INTEGER_MARCH "
        f"\"{cpu['target']['integer_march']}\"",
        f"#define SOCRV_TARGET_FP_SELECTION "
        f"\"{cpu['target']['floating_point']['selection']}\"",
        f"#define SOCRV_TARGET_SINGLE_MARCH "
        f"\"{cpu['target']['floating_point']['candidates']['single']['march']}\"",
        f"#define SOCRV_TARGET_DOUBLE_MARCH "
        f"\"{cpu['target']['floating_point']['candidates']['double']['march']}\"",
        f"#define SOCRV_SOC_CLOCK_HZ {clocks['soc_hz']}u",
        f"#define SOCRV_PERIPHERAL_CLOCK_HZ {clocks['peripheral_hz']}u",
        f"#define SOCRV_TIMER_CLOCK_HZ {clocks['timer_hz']}u",
        f"#define SOCRV_UART_BAUD {clocks['uart_baud']}u",
        f"#define SOCRV_UART_DIVISOR "
        f"(SOCRV_PERIPHERAL_CLOCK_HZ / SOCRV_UART_BAUD)",
    ]
    return header_guard("SOCRV_SOC_CONFIG_H", body)


def render_irq(contract: dict[str, object]) -> str:
    interrupts = contract["interrupts"]
    body: list[str] = []
    for name, cause in interrupts["machine_causes"].items():
        upper = name.upper()
        body.append(f"#define SOCRV_MCAUSE_{upper} {cause}u")
        body.append(f"#define SOCRV_MIE_{upper}_MASK (1u << {cause})")
    body.append("")
    for name, source in interrupts["external_sources"].items():
        body.append(f"#define SOCRV_EXT_IRQ_{name.upper()} {source}u")
        body.append(
            f"#define SOCRV_EXT_IRQ_{name.upper()}_MASK (1u << {source})"
        )
    return header_guard("SOCRV_SOC_IRQ_H", body)


def render_registers(contract: dict[str, object]) -> str:
    body: list[str] = []
    for peripheral_name, peripheral in contract["peripherals"].items():
        body.append(f"/* {peripheral_name} register offsets. */")
        for register_name, register in peripheral["registers"].items():
            prefix = f"SOCRV_{peripheral_name}_{register_name}"
            body.append(
                f"#define {prefix}_OFFSET "
                f"0x{hex_value(register['offset']):08x}u"
            )
            body.append(
                f"#define {prefix}_RESET "
                f"0x{hex_value(register['reset']):08x}u"
            )
        body.append("")
    test_status = contract["test_status"]
    body.extend(
        [
            f"#define SOCRV_TEST_PASS_MAGIC "
            f"0x{hex_value(test_status['pass_magic']):08x}u",
            f"#define SOCRV_TEST_FAIL_MAGIC "
            f"0x{hex_value(test_status['fail_magic']):08x}u",
            f"#define SOCRV_TEST_PERF_START_MAGIC "
            f"0x{hex_value(test_status['perf_start_magic']):08x}u",
            f"#define SOCRV_TEST_PERF_STOP_MAGIC "
            f"0x{hex_value(test_status['perf_stop_magic']):08x}u",
            "",
            "#define SOCRV_TIMER_CONTROL_MTIME_ENABLE (1u << 0)",
            "#define SOCRV_TIMER_CONTROL_IRQ_ENABLE   (1u << 1)",
            "#define SOCRV_UART_STATUS_RX_VALID       (1u << 0)",
            "#define SOCRV_UART_STATUS_TX_READY       (1u << 1)",
            "#define SOCRV_UART_STATUS_TX_EMPTY       (1u << 2)",
            "#define SOCRV_UART_STATUS_RX_FULL        (1u << 3)",
            "#define SOCRV_UART_CONTROL_TX_ENABLE     (1u << 0)",
            "#define SOCRV_UART_CONTROL_RX_ENABLE     (1u << 1)",
            "#define SOCRV_I2C_CONTROL_ENABLE         (1u << 0)",
            "#define SOCRV_I2C_CONTROL_SOFT_RESET     (1u << 1)",
            "#define SOCRV_I2C_CONTROL_RECOVER        (1u << 2)",
            "#define SOCRV_I2C_STATUS_BUSY            (1u << 0)",
            "#define SOCRV_I2C_STATUS_DONE            (1u << 1)",
            "#define SOCRV_I2C_STATUS_ADDR_NACK       (1u << 2)",
            "#define SOCRV_I2C_STATUS_DATA_NACK       (1u << 3)",
            "#define SOCRV_I2C_STATUS_TIMEOUT         (1u << 4)",
            "#define SOCRV_I2C_STATUS_ARB_LOST        (1u << 5)",
            "#define SOCRV_I2C_STATUS_BUS_STUCK       (1u << 6)",
            "#define SOCRV_I2C_STATUS_SCL_IN          (1u << 7)",
            "#define SOCRV_I2C_STATUS_SDA_IN          (1u << 8)",
            "#define SOCRV_I2C_STATUS_BUS_ACTIVE      (1u << 9)",
            "#define SOCRV_I2C_STATUS_BUS_READY       (1u << 10)",
            "#define SOCRV_I2C_STATUS_RX_VALID        (1u << 11)",
            "#define SOCRV_I2C_COMMAND_START          (1u << 0)",
            "#define SOCRV_I2C_COMMAND_STOP           (1u << 1)",
            "#define SOCRV_I2C_COMMAND_WRITE          (1u << 2)",
            "#define SOCRV_I2C_COMMAND_READ           (1u << 3)",
            "#define SOCRV_I2C_COMMAND_READ_NACK      (1u << 4)",
            "#define SOCRV_I2C_COMMAND_ADDRESS        (1u << 5)",
        ]
    )
    return header_guard("SOCRV_SOC_REGISTERS_H", body)


def render_linker(memory_map: dict[str, object]) -> str:
    code = memory_map["regions"]["CODE"]
    data = memory_map["regions"]["DATA"]
    return "\n".join(
        [
            "/* Generated by scripts/generate_soc_contract.py; do not edit. */",
            f"SOCRV_CODE_ORIGIN = 0x{hex_value(code['base']):08x};",
            f"SOCRV_CODE_LENGTH = 0x{hex_value(code['size']):08x};",
            f"SOCRV_DATA_ORIGIN = 0x{hex_value(data['base']):08x};",
            f"SOCRV_DATA_LENGTH = 0x{hex_value(data['size']):08x};",
            "",
        ]
    )


def rendered_outputs() -> dict[str, str]:
    memory_map, contract = load_documents()
    return {
        "memory": render_memory(memory_map),
        "config": render_config(contract),
        "irq": render_irq(contract),
        "registers": render_registers(contract),
        "linker": render_linker(memory_map),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or check software-visible SoC contract files."
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failures: list[str] = []
    for name, content in rendered_outputs().items():
        path = OUTPUTS[name]
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                failures.append(str(path.relative_to(repo_path())))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"Generated {path.relative_to(repo_path())}")
    if failures:
        raise SystemExit(
            "generated SoC contract files are stale:\n"
            + "\n".join(f"  {path}" for path in failures)
        )
    if args.check:
        print("Generated SoC contract files are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
