from __future__ import annotations

import argparse
import re
import shutil
import tempfile
from datetime import datetime
from pathlib import Path

from lib.fpga import BOARDS
from lib.hashing import sha256_file
from lib.manifest import write_json_atomic
from lib.repo import ensure_within, repo_path


RUN_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")


def sanitize_run_component(value: str) -> str:
    rendered = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("._-")
    return rendered or "competition"


def default_run_id(source: Path, *, now: datetime | None = None) -> str:
    timestamp = (now or datetime.now()).strftime("%Y%m%d_%H%M%S")
    name = source.stem if source.is_file() else source.name
    return f"{timestamp}_{sanitize_run_component(name)}"


def validate_input_source(source: Path) -> Path:
    source = source.resolve()
    if not source.exists():
        raise ValueError(f"competition source does not exist: {source}")
    if source.is_symlink():
        raise ValueError(f"competition source must not be a symlink: {source}")
    if source.is_dir():
        symlinks = [path for path in source.rglob("*") if path.is_symlink()]
        if symlinks:
            raise ValueError(
                "competition source contains symlinks; copy real files instead: "
                f"{symlinks[0]}"
            )
    elif not source.is_file():
        raise ValueError(f"competition source is not a file or directory: {source}")
    return source


def select_entry_source(original: Path, requested: str | None) -> Path:
    if requested:
        relative = Path(requested)
        if relative.is_absolute() or ".." in relative.parts:
            raise ValueError("--entry must be a path relative to the input source")
        entry = ensure_within(original / relative, original)
        if not entry.is_file():
            raise ValueError(f"competition entry source does not exist: {entry}")
        if entry.suffix.lower() != ".c":
            raise ValueError(f"competition entry source is not a C file: {entry}")
        return entry

    candidates = sorted(
        (path for path in original.rglob("*.c") if path.is_file()),
        key=lambda path: path.as_posix().lower(),
    )
    preferred = [path for path in candidates if path.name.lower() == "core_main.c"]
    if len(preferred) == 1:
        return preferred[0]
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        raise ValueError("competition input contains no C source file")
    raise ValueError(
        "competition input contains multiple C files and no unique core_main.c; "
        "use --entry <relative-path>"
    )


def source_manifest(original: Path) -> dict[str, object]:
    files = []
    for path in sorted(
        (item for item in original.rglob("*") if item.is_file()),
        key=lambda item: item.as_posix().lower(),
    ):
        files.append(
            {
                "path": path.relative_to(original.parent.parent).as_posix(),
                "size": path.stat().st_size,
                "sha256": sha256_file(path),
            }
        )
    if not files:
        raise ValueError("competition input contains no files")
    return {
        "schema_version": 1,
        "kind": "competition_source",
        "files": files,
    }


def pynq_launcher() -> str:
    return """# Auto-generated by scripts/prepare_competition_run.py.
set script_dir [file normalize [file dirname [info script]]]
set run_dir [file normalize [file join $script_dir ..]]
set repo_dir [file normalize [file join $script_dir .. .. ..]]
set image_dir [file join $run_dir images]
set build_dir [file join $run_dir vivado pynq_z2-50mhz project]
set create_script [file join $repo_dir fpga boards pynq_z2 tcl create_project.tcl]
set argv [list $build_dir $image_dir]
set argc [llength $argv]
source $create_script
"""


def kintex_launcher() -> str:
    board = BOARDS["kintex7_competition"]
    table_lines = []
    for mhz in board.supported_core_mhz:
        mult, core_divide, peripheral_divide = board.mmcm[mhz]
        table_lines.append(
            f"    {mhz} [list {mult} {core_divide} {peripheral_divide}]"
        )
    table = " \\\n".join(table_lines)
    supported = " / ".join(str(value) for value in board.supported_core_mhz)
    return f"""# Auto-generated by scripts/prepare_competition_run.py.
if {{![info exists CORE_MHZ]}} {{
    error "set CORE_MHZ before source; supported values: {supported}"
}}
if {{![string is integer -strict $CORE_MHZ]}} {{
    error "CORE_MHZ must be an integer; supported values: {supported}"
}}
set clock_table [dict create \\\n{table}]
if {{![dict exists $clock_table $CORE_MHZ]}} {{
    error "unsupported CORE_MHZ=$CORE_MHZ; supported values: {supported}"
}}
lassign [dict get $clock_table $CORE_MHZ] clock_mult core_divide peripheral_divide
set ::env(SOCRV_CLOCK_MULT) $clock_mult
set ::env(SOCRV_CORE_DIVIDE) $core_divide
set ::env(SOCRV_PERIPHERAL_DIVIDE) $peripheral_divide
set ::env(SOCRV_CORE_HZ) [expr {{$CORE_MHZ * 1000000}}]

set script_dir [file normalize [file dirname [info script]]]
set run_dir [file normalize [file join $script_dir ..]]
set repo_dir [file normalize [file join $script_dir .. .. ..]]
set image_dir [file join $run_dir images]
set build_dir [file join $run_dir vivado kintex7-${{CORE_MHZ}}mhz project]
set create_script [file join $repo_dir fpga boards kintex7_competition tcl create_project.tcl]
set argv [list $build_dir $image_dir]
set argc [llength $argv]
source $create_script
"""


def prepare_run(
    source: Path,
    *,
    run_id: str | None = None,
    entry: str | None = None,
    runs_root: Path | None = None,
    now: datetime | None = None,
) -> Path:
    source = validate_input_source(source)
    root = (runs_root or repo_path("competition_runs")).resolve()
    root.mkdir(parents=True, exist_ok=True)
    selected_run_id = run_id or default_run_id(source, now=now)
    if not RUN_ID_PATTERN.fullmatch(selected_run_id):
        raise ValueError(
            "run-id must start with a letter or digit and contain only "
            "letters, digits, '.', '_' or '-'"
        )
    run_dir = ensure_within(root / selected_run_id, root)
    if run_dir.exists():
        raise ValueError(f"competition run already exists: {run_dir}")

    with tempfile.TemporaryDirectory(prefix=f".{selected_run_id}.", dir=root) as temporary:
        temporary_run = Path(temporary)
        source_dir = temporary_run / "source"
        original = source_dir / "original"
        for name in ("software", "images", "simulation", "vivado"):
            (temporary_run / name).mkdir(parents=True, exist_ok=True)
        if source.is_file():
            original.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, original / source.name)
        else:
            shutil.copytree(source, original)

        entry_path = select_entry_source(original, entry)
        entry_relative = entry_path.relative_to(temporary_run).as_posix()
        write_json_atomic(
            source_dir / "source_manifest.json",
            source_manifest(original),
        )
        write_json_atomic(
            source_dir / "competition.json",
            {
                "schema_version": 1,
                "mode": "core_main_replacement",
                "entry_source": entry_relative,
                "extra_sources": [],
                "entry_symbol": "main",
            },
        )
        (temporary_run / "vivado" / "create_pynq_z2_project.tcl").write_text(
            pynq_launcher(), encoding="utf-8", newline="\n"
        )
        (temporary_run / "vivado" / "create_kintex7_project.tcl").write_text(
            kintex_launcher(), encoding="utf-8", newline="\n"
        )
        temporary_run.replace(run_dir)
    return run_dir


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Create one traceable competition run. The default source mode "
            "treats a unique core_main.c (or the only C file) as the CoreMark driver."
        )
    )
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--run-id")
    parser.add_argument(
        "--entry",
        help="entry C file relative to --source when automatic selection is ambiguous",
    )
    args = parser.parse_args()
    try:
        run_dir = prepare_run(
            args.source,
            run_id=args.run_id,
            entry=args.entry,
        )
    except (OSError, ValueError) as error:
        parser.error(str(error))
    relative = run_dir.relative_to(repo_path()).as_posix()
    print(f"RUN_DIR={relative}")
    print("SOURCE_MODE=core_main_replacement")
    print(f"BUILD=python scripts/build_software.py --profile contest-rtthread-coremark --run-dir \"{relative}\"")
    print(f"PYNQ_TCL={(run_dir / 'vivado' / 'create_pynq_z2_project.tcl').as_posix()}")
    print(f"KINTEX_TCL={(run_dir / 'vivado' / 'create_kintex7_project.tcl').as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
