`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: csr_file
// Generated: 2026-07-13
// Source: 053 architecture + current rv32mi contract
module csr_file (
    input  logic        clk,
    input  logic        rst,
    input  logic [11:0] read_addr_i,
    output logic [31:0] read_data_o,
    input  logic        write_valid_i,
    input  logic [11:0] write_addr_i,
    input  logic [31:0] write_data_i,
    input  logic        trap_valid_i,
    input  logic [31:0] trap_pc_i,
    input  logic [31:0] trap_cause_i,
    input  logic [31:0] trap_tval_i,
    input  logic        mret_valid_i,
    input  logic        retire_i,
    input  logic        irq_software_i,
    input  logic        irq_timer_i,
    input  logic        irq_external_i,
    output logic [31:0] mtvec_o,
    output logic [31:0] mepc_o,
    output logic [1:0]  privilege_o,
    output logic [31:0] mstatus_o,
    output logic [31:0] mscratch_o,
    output logic [31:0] mcause_o,
    output logic [31:0] mtval_o,
    output logic [31:0] pmpcfg0_o,
    output logic [31:0] pmpaddr0_o,
    output logic [31:0] mie_o,
    output logic [31:0] mip_o,
    output logic [63:0] mcycle_o,
    output logic [63:0] minstret_o,
    output logic        tselect_o,
    output logic [31:0] tdata1_0_o,
    output logic [31:0] tdata1_1_o,
    output logic [31:0] tdata2_0_o,
    output logic [31:0] tdata2_1_o,
    output logic [31:0] tcontrol_o,
    output logic        interrupt_pending_o,
    output logic [31:0] interrupt_cause_o
);
    logic [31:0] mstatus_q, mtvec_q, mscratch_q, mepc_q, mcause_q, mtval_q;
    logic [31:0] pmpcfg0_q, pmpaddr0_q;
    logic [31:0] mie_q, mip;
    logic [31:0] mcounteren_q, mcountinhibit_q;
    logic [63:0] mcycle_q, minstret_q;
    logic tselect_q;
    logic [31:0] tdata1_q [0:1];
    logic [31:0] tdata2_q [0:1];
    logic [31:0] tcontrol_q;
    logic [1:0] privilege_q;

    function automatic logic [31:0] mstatus_warl(input logic [31:0] value);
        logic [31:0] result;
        begin
            result = value & 32'h0002_1888;
            if (!(value[12:11] inside {2'b00, 2'b11}))
                result[12:11] = 2'b00;
            return result;
        end
    endfunction

    assign mtvec_o = mtvec_q;
    assign mepc_o  = {mepc_q[31:2], 2'b00};
    assign privilege_o = privilege_q;
    assign mstatus_o = mstatus_q;
    assign mscratch_o = mscratch_q;
    assign mcause_o = mcause_q;
    assign mtval_o = mtval_q;
    assign pmpcfg0_o = pmpcfg0_q;
    assign pmpaddr0_o = pmpaddr0_q;
    assign mie_o = mie_q;
    assign mip_o = mip;
    assign mcycle_o = mcycle_q;
    assign minstret_o = minstret_q;
    assign tselect_o = tselect_q;
    assign tdata1_0_o = tdata1_q[0];
    assign tdata1_1_o = tdata1_q[1];
    assign tdata2_0_o = tdata2_q[0];
    assign tdata2_1_o = tdata2_q[1];
    assign tcontrol_o = tcontrol_q;

    always_comb begin
        mip = 32'd0;
        mip[3] = irq_software_i;
        mip[7] = irq_timer_i;
        mip[11] = irq_external_i;
        interrupt_pending_o = 1'b0;
        interrupt_cause_o = 32'd0;
        if ((privilege_q != 2'b11) || mstatus_q[3]) begin
            if (mip[11] && mie_q[11]) begin
                interrupt_pending_o = 1'b1;
                interrupt_cause_o = 32'h8000_000b;
            end else if (mip[7] && mie_q[7]) begin
                interrupt_pending_o = 1'b1;
                interrupt_cause_o = 32'h8000_0007;
            end else if (mip[3] && mie_q[3]) begin
                interrupt_pending_o = 1'b1;
                interrupt_cause_o = 32'h8000_0003;
            end
        end
    end

    always_comb begin
        read_data_o = 32'd0;
        unique case (read_addr_i)
            12'h300: read_data_o = mstatus_q;
            12'h301: read_data_o = 32'h4010_1100;
            12'h304: read_data_o = mie_q;
            12'h305: read_data_o = mtvec_q;
            12'h306: read_data_o = mcounteren_q;
            12'h320: read_data_o = mcountinhibit_q;
            12'h340: read_data_o = mscratch_q;
            12'h341: read_data_o = mepc_q;
            12'h342: read_data_o = mcause_q;
            12'h343: read_data_o = mtval_q;
            12'h344: read_data_o = mip;
            12'h3A0: read_data_o = pmpcfg0_q;
            12'h3B0: read_data_o = pmpaddr0_q;
            12'h7A0: read_data_o = {31'd0, tselect_q};
            12'h7A1: read_data_o = tdata1_q[tselect_q];
            12'h7A2: read_data_o = tdata2_q[tselect_q];
            12'h7A5: read_data_o = tcontrol_q;
            12'hB00, 12'hC00: read_data_o = mcycle_q[31:0];
            12'hB80, 12'hC80: read_data_o = mcycle_q[63:32];
            12'hB02, 12'hC02: read_data_o = minstret_q[31:0];
            12'hB82, 12'hC82: read_data_o = minstret_q[63:32];
            12'hF14: read_data_o = 32'd0;
            default: read_data_o = 32'd0;
        endcase
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            mstatus_q  <= 32'd0;
            mtvec_q    <= 32'd0;
            mscratch_q <= 32'd0;
            mepc_q     <= 32'd0;
            mcause_q   <= 32'd0;
            mtval_q    <= 32'd0;
            pmpcfg0_q  <= 32'd0;
            pmpaddr0_q <= 32'd0;
            privilege_q <= 2'b11;
            mie_q       <= 32'd0;
            mcounteren_q <= 32'd0;
            mcountinhibit_q <= 32'd0;
            mcycle_q <= 64'd0;
            minstret_q <= 64'd0;
            tselect_q <= 1'b0;
            tdata1_q[0] <= 32'd0;
            tdata1_q[1] <= 32'd0;
            tdata2_q[0] <= 32'd0;
            tdata2_q[1] <= 32'd0;
            tcontrol_q <= 32'd0;
        end else begin
            if (!mcountinhibit_q[0]) mcycle_q <= mcycle_q + 64'd1;
            if (retire_i && !mcountinhibit_q[2] &&
                !(write_valid_i &&
                  (write_addr_i == 12'hB02 || write_addr_i == 12'hB82)))
                minstret_q <= minstret_q + 64'd1;

            if (trap_valid_i) begin
                mepc_q <= {trap_pc_i[31:2], 2'b00};
                mcause_q <= trap_cause_i;
                mtval_q <= trap_tval_i;
                mstatus_q[7] <= mstatus_q[3];
                mstatus_q[3] <= 1'b0;
                mstatus_q[12:11] <= privilege_q;
                privilege_q <= 2'b11;
            end else begin
                if (mret_valid_i) begin
                    mstatus_q[3] <= mstatus_q[7];
                    mstatus_q[7] <= 1'b1;
                    mstatus_q[12:11] <= 2'b00;
                    privilege_q <= mstatus_q[12:11];
                end
                if (write_valid_i) begin
                    unique case (write_addr_i)
                        12'h300: mstatus_q <= mstatus_warl(write_data_i);
                        12'h304: mie_q <= write_data_i & 32'h0000_0888;
                        12'h305: mtvec_q <= {write_data_i[31:2], 1'b0, write_data_i[0]};
                        12'h306: mcounteren_q <= write_data_i & 32'h0000_0005;
                        12'h320: mcountinhibit_q <= write_data_i & 32'h0000_0005;
                        12'h340: mscratch_q <= write_data_i;
                        12'h341: mepc_q <= {write_data_i[31:2], 2'b00};
                        12'h342: mcause_q <= write_data_i;
                        12'h343: mtval_q <= write_data_i;
                        12'h3A0: pmpcfg0_q <= write_data_i;
                        12'h3B0: pmpaddr0_q <= write_data_i;
                        12'h7A0: tselect_q <= write_data_i[0];
                        12'h7A1: tdata1_q[tselect_q] <= write_data_i;
                        12'h7A2: tdata2_q[tselect_q] <= write_data_i;
                        12'h7A5: tcontrol_q <= write_data_i & 32'h0000_0008;
                        12'hB00: mcycle_q[31:0] <= write_data_i;
                        12'hB80: mcycle_q[63:32] <= write_data_i;
                        12'hB02: minstret_q[31:0] <= write_data_i;
                        12'hB82: minstret_q[63:32] <= write_data_i;
                        default: begin end
                    endcase
                end
            end
        end
    end
endmodule
