`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: frontend
// Generated: 2026-07-13
// Source: 053 architecture
module frontend (
    input  logic clk,
    input  logic rst,
    input  logic redirect_valid_i,
    input  logic [31:0] redirect_target_i,
    output logic [31:0] irom_addr_o,
    output logic irom_ena_o,
    input  logic irom_req_ready_i,
    input  logic irom_resp_valid_i,
    input  logic [31:0] irom_data_i,
    input  logic irom_resp_err_i,
    output logic fetch_valid_o,
    output core_types_pkg::fetch_entry_t fetch_entry_o,
    input  logic fetch_ready_i,
    input  logic predictor_update_valid_i,
    input  logic [31:0] predictor_update_pc_i,
    input  logic predictor_update_taken_i,
    input  logic [31:0] predictor_update_target_i,
    input  core_types_pkg::pred_kind_e predictor_update_kind_i,
    input  logic [1:0] predictor_update_pred_counter_i,
    input  logic [core_config_pkg::GSHARE_HISTORY_BITS-1:0]
                 predictor_update_pred_index_i,
    input  logic predictor_commit_call_i,
    input  logic predictor_commit_return_i,
    input  logic [31:0] predictor_commit_link_i
);
    import core_config_pkg::*;
    import core_types_pkg::*;

    localparam int unsigned COUNT_W = $clog2(FETCH_QUEUE_DEPTH + 1);
    localparam int unsigned PTR_W = $clog2(FETCH_QUEUE_DEPTH);
    localparam int unsigned EPOCH_W = 8;
    typedef logic [PTR_W-1:0] pending_ptr_t;
    typedef logic [COUNT_W-1:0] pending_count_t;

    logic [COUNT_W-1:0] queue_count;
    logic [31:0] candidate_pc_q;
    logic candidate_valid_q;
    logic [EPOCH_W-1:0] current_epoch_q;

    logic [31:0] pending_pc_q [0:FETCH_QUEUE_DEPTH-1];
    logic [EPOCH_W-1:0] pending_epoch_q [0:FETCH_QUEUE_DEPTH-1];
    logic pending_pred_valid_q [0:FETCH_QUEUE_DEPTH-1];
    logic [31:0] pending_pred_next_pc_q [0:FETCH_QUEUE_DEPTH-1];
    pred_kind_e pending_pred_kind_q [0:FETCH_QUEUE_DEPTH-1];
    logic pending_pred_hit_q [0:FETCH_QUEUE_DEPTH-1];
    logic [1:0] pending_pred_counter_q [0:FETCH_QUEUE_DEPTH-1];
    logic [GSHARE_HISTORY_BITS-1:0]
          pending_pred_index_q [0:FETCH_QUEUE_DEPTH-1];
    pending_ptr_t pending_head_q;
    pending_ptr_t pending_tail_q;
    pending_count_t pending_count_q;

    // The predictor is a one-cycle synchronous lookup.  These registers tag
    // its next result with the pending entry allocated by the matching memory
    // request.
    pending_ptr_t predictor_pending_ptr_q;
    logic [EPOCH_W-1:0] predictor_epoch_q;

    logic predictor_result_valid;
    logic predicted_hit;
    logic [31:0] predicted_next_pc;
    pred_kind_e predicted_kind;
    logic [1:0] predicted_counter;
    logic [GSHARE_HISTORY_BITS-1:0] predicted_index;
    logic prediction_matches_epoch;
    logic prediction_matches_head;
    logic head_is_current;
    logic head_prediction_ready;
    logic capacity_available;
    logic queue_push;
    logic queue_pop;
    logic request_fire;
    logic response_fire;
    fetch_entry_t push_entry;

    branch_predictor u_branch_predictor (
        .clk(clk), .rst(rst), .predict_read_en_i(request_fire),
        .predict_pc_i(irom_addr_o), .predict_valid_o(predictor_result_valid),
        .predict_next_pc_o(predicted_next_pc),
        .predict_kind_o(predicted_kind), .predict_hit_o(predicted_hit),
        .predict_counter_o(predicted_counter),
        .predict_index_o(predicted_index),
        .update_valid_i(predictor_update_valid_i),
        .update_pc_i(predictor_update_pc_i),
        .update_taken_i(predictor_update_taken_i),
        .update_target_i(predictor_update_target_i),
        .update_kind_i(predictor_update_kind_i),
        .update_pred_counter_i(predictor_update_pred_counter_i),
        .update_pred_index_i(predictor_update_pred_index_i),
        .commit_call_i(predictor_commit_call_i),
        .commit_return_i(predictor_commit_return_i),
        .commit_link_i(predictor_commit_link_i)
    );

    assign prediction_matches_epoch = predictor_result_valid &&
                                      predictor_epoch_q == current_epoch_q;
    assign irom_addr_o = candidate_valid_q ? candidate_pc_q :
                         predicted_next_pc;
    assign queue_pop = fetch_valid_o && fetch_ready_i && !redirect_valid_i;
    // Every accepted request reserves one fetch-queue slot until its response
    // is either enqueued or discarded.  A simultaneous backend pop returns a
    // credit soon enough to sustain one request per cycle at the full boundary.
    assign capacity_available =
        ({1'b0, queue_count} + {1'b0, pending_count_q} <
         (COUNT_W+1)'(FETCH_QUEUE_DEPTH)) || queue_pop;
    assign irom_ena_o = !rst && !redirect_valid_i && capacity_available &&
                        (candidate_valid_q || prediction_matches_epoch);
    assign request_fire = irom_ena_o && irom_req_ready_i;
    assign response_fire = irom_resp_valid_i && pending_count_q != 0;

    assign prediction_matches_head = predictor_result_valid &&
                                     predictor_pending_ptr_q == pending_head_q &&
                                     predictor_epoch_q ==
                                         pending_epoch_q[pending_head_q];
    assign head_is_current = pending_count_q != 0 &&
                             pending_epoch_q[pending_head_q] == current_epoch_q;
    assign head_prediction_ready = pending_pred_valid_q[pending_head_q] ||
                                   prediction_matches_head;
    assign queue_push = response_fire && head_is_current &&
                        head_prediction_ready && !redirect_valid_i;

    always_comb begin
        push_entry = '0;
        push_entry.pc = pending_pc_q[pending_head_q];
        push_entry.instr = irom_data_i;
        push_entry.access_fault = irom_resp_err_i;
        if (prediction_matches_head) begin
            push_entry.pred_next_pc = predicted_next_pc;
            push_entry.pred_kind = predicted_kind;
            push_entry.pred_hit = predicted_hit;
            push_entry.pred_counter = predicted_counter;
            push_entry.pred_index = predicted_index;
        end else begin
            push_entry.pred_next_pc =
                pending_pred_next_pc_q[pending_head_q];
            push_entry.pred_kind = pending_pred_kind_q[pending_head_q];
            push_entry.pred_hit = pending_pred_hit_q[pending_head_q];
            push_entry.pred_counter =
                pending_pred_counter_q[pending_head_q];
            push_entry.pred_index = pending_pred_index_q[pending_head_q];
        end
    end

    fetch_queue u_fetch_queue (
        .clk(clk), .rst(rst), .flush_i(redirect_valid_i),
        .push_i(queue_push), .push_entry_i(push_entry), .pop_i(queue_pop),
        .valid_o(fetch_valid_o), .head_o(fetch_entry_o),
        .count_o(queue_count)
    );

    always_ff @(posedge clk) begin
        if (rst) begin
            candidate_pc_q <= RESET_PC;
            candidate_valid_q <= 1'b1;
            current_epoch_q <= '0;
            pending_head_q <= '0;
            pending_tail_q <= '0;
            pending_count_q <= '0;
            predictor_pending_ptr_q <= '0;
            predictor_epoch_q <= '0;
        end else begin
            if (redirect_valid_i) begin
                candidate_pc_q <= redirect_target_i;
                candidate_valid_q <= 1'b1;
                current_epoch_q <= current_epoch_q + 1'b1;
            end else begin
                if (request_fire) begin
                    candidate_valid_q <= 1'b0;
                end else if (!candidate_valid_q &&
                             prediction_matches_epoch) begin
                    candidate_pc_q <= predicted_next_pc;
                    candidate_valid_q <= 1'b1;
                end
            end

            if (request_fire) begin
                pending_pc_q[pending_tail_q] <= irom_addr_o;
                pending_epoch_q[pending_tail_q] <= current_epoch_q;
                pending_pred_valid_q[pending_tail_q] <= 1'b0;
                predictor_pending_ptr_q <= pending_tail_q;
                predictor_epoch_q <= current_epoch_q;
                pending_tail_q <= pending_tail_q + 1'b1;
            end

            // A latency-one ROM response can consume the entry in the same
            // cycle as its predictor result.  In that case push_entry uses the
            // direct bypass and the array write is intentionally suppressed,
            // which also makes same-cycle FIFO slot reuse safe.
            if (!redirect_valid_i && predictor_result_valid &&
                !(response_fire &&
                  predictor_pending_ptr_q == pending_head_q)) begin
                pending_pred_valid_q[predictor_pending_ptr_q] <= 1'b1;
                pending_pred_next_pc_q[predictor_pending_ptr_q] <=
                    predicted_next_pc;
                pending_pred_kind_q[predictor_pending_ptr_q] <=
                    predicted_kind;
                pending_pred_hit_q[predictor_pending_ptr_q] <= predicted_hit;
                pending_pred_counter_q[predictor_pending_ptr_q] <=
                    predicted_counter;
                pending_pred_index_q[predictor_pending_ptr_q] <=
                    predicted_index;
            end

            if (response_fire)
                pending_head_q <= pending_head_q + 1'b1;
            unique case ({request_fire, response_fire})
                2'b10: pending_count_q <= pending_count_q + 1'b1;
                2'b01: pending_count_q <= pending_count_q - 1'b1;
                default: begin end
            endcase
        end
    end

`ifndef SYNTHESIS
    initial begin
        assert (FETCH_QUEUE_DEPTH >= 2);
        assert ((FETCH_QUEUE_DEPTH & (FETCH_QUEUE_DEPTH - 1)) == 0);
    end

    always_ff @(posedge clk) begin
        if (!rst) begin
            assert (pending_count_q <=
                    pending_count_t'(FETCH_QUEUE_DEPTH));
            assert ({1'b0, queue_count} + {1'b0, pending_count_q} <=
                    (COUNT_W+1)'(FETCH_QUEUE_DEPTH));
            if (irom_resp_valid_i) assert (pending_count_q != 0);
            if (response_fire && head_is_current && !redirect_valid_i)
                assert (head_prediction_ready);
        end
    end
`endif
endmodule
