`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: frontend
// Generated: 2026-07-13
// Source: 053 architecture
module frontend (
    input  logic clk,
    input  logic rst,
    input  logic redirect_valid_i,
    input  logic [31:0] redirect_target_i,
    output logic [31:0] irom_addr_o,
    output logic irom_ena_o,
    input  logic irom_req_ready_i,
    input  logic irom_resp_valid_i,
    input  logic [31:0] irom_data_i,
    input  logic irom_resp_err_i,
    output logic fetch_valid_o,
    output core_types_pkg::fetch_entry_t fetch_entry_o,
    input  logic fetch_ready_i,
    input  logic predictor_update_valid_i,
    input  logic [31:0] predictor_update_pc_i,
    input  logic predictor_update_taken_i,
    input  logic [31:0] predictor_update_target_i,
    input  core_types_pkg::pred_kind_e predictor_update_kind_i,
    input  logic [1:0] predictor_update_pred_counter_i,
    input  logic [core_config_pkg::GSHARE_HISTORY_BITS-1:0] predictor_update_pred_index_i,
    input  logic predictor_commit_call_i,
    input  logic predictor_commit_return_i,
    input  logic [31:0] predictor_commit_link_i
);
    import core_config_pkg::*;
    import core_types_pkg::*;

    localparam int unsigned COUNT_W = $clog2(FETCH_QUEUE_DEPTH + 1);
    logic [COUNT_W-1:0] queue_count;
    logic [31:0] fetch_pc_q;
    logic request_outstanding_q;
    logic drop_response_q;
    logic [31:0] pending_pc_q;
    logic predictor_result_valid, predicted_hit;
    logic [31:0] predicted_next_pc;
    pred_kind_e predicted_kind;
    logic [1:0] predicted_counter;
    logic [GSHARE_HISTORY_BITS-1:0] predicted_index;
    logic prediction_valid_q;
    logic [31:0] predicted_next_pc_q;
    pred_kind_e predicted_kind_q;
    logic predicted_hit_q;
    logic [1:0] predicted_counter_q;
    logic [GSHARE_HISTORY_BITS-1:0] predicted_index_q;
    fetch_entry_t push_entry;
    logic queue_push, queue_pop, request_fire, response_fire;

    branch_predictor u_branch_predictor (
        .clk(clk), .rst(rst), .predict_read_en_i(request_fire),
        .predict_pc_i(fetch_pc_q), .predict_valid_o(predictor_result_valid),
        .predict_next_pc_o(predicted_next_pc), .predict_kind_o(predicted_kind),
        .predict_hit_o(predicted_hit), .predict_counter_o(predicted_counter),
        .predict_index_o(predicted_index),
        .update_valid_i(predictor_update_valid_i), .update_pc_i(predictor_update_pc_i),
        .update_taken_i(predictor_update_taken_i), .update_target_i(predictor_update_target_i),
        .update_kind_i(predictor_update_kind_i),
        .update_pred_counter_i(predictor_update_pred_counter_i),
        .update_pred_index_i(predictor_update_pred_index_i),
        .commit_call_i(predictor_commit_call_i),
        .commit_return_i(predictor_commit_return_i), .commit_link_i(predictor_commit_link_i)
    );

    // SocRV instruction memory is a backpressured HXI port.  Reserve one queue
    // slot when a request is accepted, retain the synchronous predictor result,
    // and advance the fetch PC only when the matching response arrives.
    assign irom_addr_o = fetch_pc_q;
    assign irom_ena_o = !rst && !redirect_valid_i &&
                        !request_outstanding_q &&
                        (queue_count < COUNT_W'(FETCH_QUEUE_DEPTH));
    assign request_fire = irom_ena_o && irom_req_ready_i;
    assign response_fire = request_outstanding_q && irom_resp_valid_i;
    assign queue_push = response_fire && !drop_response_q &&
                        (prediction_valid_q || predictor_result_valid) &&
                        !redirect_valid_i;
    assign queue_pop = fetch_valid_o && fetch_ready_i && !redirect_valid_i;
    always_comb begin
        push_entry = '0;
        push_entry.pc = pending_pc_q;
        push_entry.instr = irom_data_i;
        push_entry.access_fault = irom_resp_err_i;
        push_entry.pred_next_pc = predictor_result_valid ? predicted_next_pc :
                                  predicted_next_pc_q;
        push_entry.pred_kind = predictor_result_valid ? predicted_kind : predicted_kind_q;
        push_entry.pred_hit = predictor_result_valid ? predicted_hit : predicted_hit_q;
        push_entry.pred_counter = predictor_result_valid ? predicted_counter :
                                   predicted_counter_q;
        push_entry.pred_index = predictor_result_valid ? predicted_index : predicted_index_q;
    end

    fetch_queue u_fetch_queue (
        .clk(clk), .rst(rst), .flush_i(redirect_valid_i),
        .push_i(queue_push), .push_entry_i(push_entry), .pop_i(queue_pop),
        .valid_o(fetch_valid_o), .head_o(fetch_entry_o), .count_o(queue_count)
    );

    always_ff @(posedge clk) begin
        if (rst) begin
            fetch_pc_q <= RESET_PC;
            request_outstanding_q <= 1'b0;
            drop_response_q <= 1'b0;
            pending_pc_q <= '0;
            prediction_valid_q <= 1'b0;
            predicted_next_pc_q <= '0;
            predicted_kind_q <= PRED_NONE;
            predicted_hit_q <= 1'b0;
            predicted_counter_q <= 2'b01;
            predicted_index_q <= '0;
        end else if (redirect_valid_i) begin
            fetch_pc_q <= redirect_target_i;
            prediction_valid_q <= 1'b0;
            if (response_fire) begin
                request_outstanding_q <= 1'b0;
                drop_response_q <= 1'b0;
            end else if (request_outstanding_q) begin
                drop_response_q <= 1'b1;
            end
        end else begin
            if (predictor_result_valid) begin
                prediction_valid_q <= 1'b1;
                predicted_next_pc_q <= predicted_next_pc;
                predicted_kind_q <= predicted_kind;
                predicted_hit_q <= predicted_hit;
                predicted_counter_q <= predicted_counter;
                predicted_index_q <= predicted_index;
            end
            if (request_fire) begin
                request_outstanding_q <= 1'b1;
                drop_response_q <= 1'b0;
                pending_pc_q <= fetch_pc_q;
                prediction_valid_q <= 1'b0;
            end
            if (response_fire) begin
                request_outstanding_q <= 1'b0;
                drop_response_q <= 1'b0;
                prediction_valid_q <= 1'b0;
                if (!drop_response_q) begin
                    fetch_pc_q <= predictor_result_valid ? predicted_next_pc :
                                  predicted_next_pc_q;
                end
            end
        end
    end

`ifndef SYNTHESIS
    always_ff @(posedge clk) begin
        if (!rst) begin
            assert (queue_count + COUNT_W'(request_outstanding_q) <=
                    COUNT_W'(FETCH_QUEUE_DEPTH));
            if (response_fire && !drop_response_q)
                assert (prediction_valid_q || predictor_result_valid);
        end
    end
`endif
endmodule
